CREATE TABLE `alerts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` integer NOT NULL,
	`symbol` text(50) NOT NULL,
	`side` text(10) NOT NULL,
	`tier` text(20) NOT NULL,
	`tier_numeric` integer NOT NULL,
	`strength` real NOT NULL,
	`entry_price` real NOT NULL,
	`sl` real NOT NULL,
	`tp1` real NOT NULL,
	`tp2` real NOT NULL,
	`tp3` real NOT NULL,
	`main_tp` real NOT NULL,
	`atr` real NOT NULL,
	`volume_ratio` real NOT NULL,
	`session` text(50) NOT NULL,
	`regime` text(50) NOT NULL,
	`regime_confidence` real NOT NULL,
	`mtf_agreement` real NOT NULL,
	`leverage` integer NOT NULL,
	`in_ob` integer NOT NULL,
	`in_fvg` integer NOT NULL,
	`ob_score` real NOT NULL,
	`fvg_score` real NOT NULL,
	`institutional_flow` real,
	`accumulation` real,
	`volume_climax` integer,
	`latency` integer NOT NULL,
	`raw_json` text NOT NULL,
	`created_at` text NOT NULL
);
