CREATE TABLE `bot_actions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`action_type` text NOT NULL,
	`symbol` text,
	`side` text,
	`tier` text,
	`alert_id` integer,
	`position_id` integer,
	`reason` text NOT NULL,
	`details` text,
	`success` integer NOT NULL,
	`error_message` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`alert_id`) REFERENCES `alerts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`position_id`) REFERENCES `bot_positions`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `bot_positions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`alert_id` integer,
	`symbol` text NOT NULL,
	`side` text NOT NULL,
	`tier` text NOT NULL,
	`entry_price` real NOT NULL,
	`quantity` real NOT NULL,
	`leverage` integer NOT NULL,
	`stop_loss` real NOT NULL,
	`tp1_price` real,
	`tp2_price` real,
	`tp3_price` real,
	`main_tp_price` real NOT NULL,
	`tp1_hit` integer DEFAULT false NOT NULL,
	`tp2_hit` integer DEFAULT false NOT NULL,
	`tp3_hit` integer DEFAULT false NOT NULL,
	`current_sl` real NOT NULL,
	`position_value` real NOT NULL,
	`initial_margin` real NOT NULL,
	`unrealised_pnl` real DEFAULT 0 NOT NULL,
	`confirmation_count` integer DEFAULT 1 NOT NULL,
	`confidence_score` real NOT NULL,
	`opened_at` text NOT NULL,
	`last_updated` text NOT NULL,
	`bybit_order_id` text,
	`status` text DEFAULT 'open' NOT NULL,
	FOREIGN KEY (`alert_id`) REFERENCES `alerts`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `bot_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`bot_enabled` integer DEFAULT false NOT NULL,
	`position_size_mode` text DEFAULT 'percent' NOT NULL,
	`position_size_percent` real DEFAULT 2 NOT NULL,
	`position_size_fixed` real DEFAULT 100 NOT NULL,
	`leverage_mode` text DEFAULT 'from_alert' NOT NULL,
	`leverage_fixed` integer DEFAULT 10 NOT NULL,
	`tier_filtering_mode` text DEFAULT 'all' NOT NULL,
	`disabled_tiers` text DEFAULT '[]' NOT NULL,
	`tp_strategy` text DEFAULT 'multiple' NOT NULL,
	`max_concurrent_positions` integer DEFAULT 10 NOT NULL,
	`same_symbol_behavior` text DEFAULT 'track_confirmations' NOT NULL,
	`opposite_direction_strategy` text DEFAULT 'market_reversal' NOT NULL,
	`reversal_wait_bars` integer DEFAULT 1 NOT NULL,
	`reversal_min_strength` real DEFAULT 0.25 NOT NULL,
	`emergency_can_reverse` integer DEFAULT true NOT NULL,
	`emergency_override_mode` text DEFAULT 'only_profit' NOT NULL,
	`emergency_min_profit_percent` real DEFAULT 0 NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `position_history` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`position_id` integer NOT NULL,
	`symbol` text NOT NULL,
	`side` text NOT NULL,
	`tier` text NOT NULL,
	`entry_price` real NOT NULL,
	`close_price` real NOT NULL,
	`quantity` real NOT NULL,
	`leverage` integer NOT NULL,
	`pnl` real NOT NULL,
	`pnl_percent` real NOT NULL,
	`close_reason` text NOT NULL,
	`tp1_hit` integer DEFAULT false NOT NULL,
	`tp2_hit` integer DEFAULT false NOT NULL,
	`tp3_hit` integer DEFAULT false NOT NULL,
	`confirmation_count` integer DEFAULT 1 NOT NULL,
	`opened_at` text NOT NULL,
	`closed_at` text NOT NULL,
	`duration_minutes` integer,
	FOREIGN KEY (`position_id`) REFERENCES `bot_positions`(`id`) ON UPDATE no action ON DELETE no action
);
