import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core';

export const alerts = sqliteTable('alerts', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  timestamp: integer('timestamp').notNull(),
  symbol: text('symbol', { length: 50 }).notNull(),
  side: text('side', { length: 10 }).notNull(),
  tier: text('tier', { length: 20 }).notNull(),
  tierNumeric: integer('tier_numeric').notNull(),
  strength: real('strength').notNull(),
  entryPrice: real('entry_price').notNull(),
  sl: real('sl').notNull(),
  tp1: real('tp1').notNull(),
  tp2: real('tp2').notNull(),
  tp3: real('tp3').notNull(),
  mainTp: real('main_tp').notNull(),
  atr: real('atr').notNull(),
  volumeRatio: real('volume_ratio').notNull(),
  session: text('session', { length: 50 }).notNull(),
  regime: text('regime', { length: 50 }).notNull(),
  regimeConfidence: real('regime_confidence').notNull(),
  mtfAgreement: real('mtf_agreement').notNull(),
  leverage: integer('leverage').notNull(),
  inOb: integer('in_ob', { mode: 'boolean' }).notNull(),
  inFvg: integer('in_fvg', { mode: 'boolean' }).notNull(),
  obScore: real('ob_score').notNull(),
  fvgScore: real('fvg_score').notNull(),
  institutionalFlow: real('institutional_flow'),
  accumulation: real('accumulation'),
  volumeClimax: integer('volume_climax', { mode: 'boolean' }),
  latency: integer('latency').notNull(),
  rawJson: text('raw_json').notNull(),
  executionStatus: text('execution_status').notNull().default('pending'),
  rejectionReason: text('rejection_reason'),
  createdAt: text('created_at').notNull(),
});

export const botSettings = sqliteTable('bot_settings', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  botEnabled: integer('bot_enabled', { mode: 'boolean' }).notNull().default(false),
  positionSizeMode: text('position_size_mode').notNull().default('percent'),
  positionSizePercent: real('position_size_percent').notNull().default(2.0),
  positionSizeFixed: real('position_size_fixed').notNull().default(100.0),
  leverageMode: text('leverage_mode').notNull().default('from_alert'),
  leverageFixed: integer('leverage_fixed').notNull().default(10),
  tierFilteringMode: text('tier_filtering_mode').notNull().default('all'),
  disabledTiers: text('disabled_tiers').notNull().default('[]'),
  tpStrategy: text('tp_strategy').notNull().default('multiple'),
  maxConcurrentPositions: integer('max_concurrent_positions').notNull().default(10),
  sameSymbolBehavior: text('same_symbol_behavior').notNull().default('track_confirmations'),
  oppositeDirectionStrategy: text('opposite_direction_strategy').notNull().default('market_reversal'),
  reversalWaitBars: integer('reversal_wait_bars').notNull().default(1),
  reversalMinStrength: real('reversal_min_strength').notNull().default(0.25),
  emergencyCanReverse: integer('emergency_can_reverse', { mode: 'boolean' }).notNull().default(true),
  emergencyOverrideMode: text('emergency_override_mode').notNull().default('only_profit'),
  emergencyMinProfitPercent: real('emergency_min_profit_percent').notNull().default(0.0),
  useDefaultSlTp: integer('use_default_sl_tp', { mode: 'boolean' }).notNull().default(false),
  defaultSlPercent: real('default_sl_percent').notNull().default(2.0),
  defaultTp1Percent: real('default_tp1_percent').notNull().default(2.0),
  defaultTp2Percent: real('default_tp2_percent').notNull().default(4.0),
  defaultTp3Percent: real('default_tp3_percent').notNull().default(6.0),
  apiKey: text('api_key'),
  apiSecret: text('api_secret'),
  exchange: text('exchange').notNull().default('bybit'),
  environment: text('environment').notNull().default('demo'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const botPositions = sqliteTable('bot_positions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  alertId: integer('alert_id').references(() => alerts.id),
  symbol: text('symbol').notNull(),
  side: text('side').notNull(),
  tier: text('tier').notNull(),
  entryPrice: real('entry_price').notNull(),
  quantity: real('quantity').notNull(),
  leverage: integer('leverage').notNull(),
  stopLoss: real('stop_loss').notNull(),
  tp1Price: real('tp1_price'),
  tp2Price: real('tp2_price'),
  tp3Price: real('tp3_price'),
  mainTpPrice: real('main_tp_price').notNull(),
  tp1Hit: integer('tp1_hit', { mode: 'boolean' }).notNull().default(false),
  tp2Hit: integer('tp2_hit', { mode: 'boolean' }).notNull().default(false),
  tp3Hit: integer('tp3_hit', { mode: 'boolean' }).notNull().default(false),
  currentSl: real('current_sl').notNull(),
  positionValue: real('position_value').notNull(),
  initialMargin: real('initial_margin').notNull(),
  unrealisedPnl: real('unrealised_pnl').notNull().default(0.0),
  confirmationCount: integer('confirmation_count').notNull().default(1),
  confidenceScore: real('confidence_score').notNull(),
  openedAt: text('opened_at').notNull(),
  lastUpdated: text('last_updated').notNull(),
  bybitOrderId: text('bybit_order_id'),
  tp2OrderId: text('tp2_order_id'),
  tp3OrderId: text('tp3_order_id'),
  closedAt: text('closed_at'),
  closeReason: text('close_reason'),
  status: text('status').notNull().default('open'),
});

export const botActions = sqliteTable('bot_actions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  actionType: text('action_type').notNull(),
  symbol: text('symbol'),
  side: text('side'),
  tier: text('tier'),
  alertId: integer('alert_id').references(() => alerts.id),
  positionId: integer('position_id').references(() => botPositions.id),
  reason: text('reason').notNull(),
  details: text('details'),
  success: integer('success', { mode: 'boolean' }).notNull(),
  errorMessage: text('error_message'),
  createdAt: text('created_at').notNull(),
});

export const positionHistory = sqliteTable('position_history', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  positionId: integer('position_id').references(() => botPositions.id).notNull(),
  symbol: text('symbol').notNull(),
  side: text('side').notNull(),
  tier: text('tier').notNull(),
  entryPrice: real('entry_price').notNull(),
  closePrice: real('close_price').notNull(),
  quantity: real('quantity').notNull(),
  leverage: integer('leverage').notNull(),
  pnl: real('pnl').notNull(),
  pnlPercent: real('pnl_percent').notNull(),
  closeReason: text('close_reason').notNull(),
  tp1Hit: integer('tp1_hit', { mode: 'boolean' }).notNull().default(false),
  tp2Hit: integer('tp2_hit', { mode: 'boolean' }).notNull().default(false),
  tp3Hit: integer('tp3_hit', { mode: 'boolean' }).notNull().default(false),
  confirmationCount: integer('confirmation_count').notNull().default(1),
  openedAt: text('opened_at').notNull(),
  closedAt: text('closed_at').notNull(),
  durationMinutes: integer('duration_minutes'),
});

export const botLogs = sqliteTable('bot_logs', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  timestamp: integer('timestamp').notNull(),
  level: text('level', { length: 20 }).notNull(), // error, warning, info, success
  action: text('action', { length: 100 }).notNull(), // webhook_received, position_opened, etc.
  message: text('message').notNull(),
  details: text('details'), // JSON string with additional data
  alertId: integer('alert_id').references(() => alerts.id),
  positionId: integer('position_id').references(() => botPositions.id),
  createdAt: integer('created_at').notNull(),
});